"""Report generation and run-over-run comparison.

Format follows docs/proposals/AGENT-001-observation-agent/
5-REPORTING-SPECIFICATION.md exactly. The New/Repeated/Resolved
Findings sections require comparing this run against the previous
one — implemented here as a small JSON snapshot written after each
run (`last_run_observations.json`), read back at the start of the
next one. This is the "bookkeeping delta-tracking capability" that
specification calls for, not a new governance concept.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from .models import Confidence, Observation


def _observation_key(obs: Observation) -> str:
    """A stable identity for comparing the same finding across runs —
    the check that produced it plus what it's about, not the full
    evidence text (which may reformat harmlessly between runs)."""
    first_path = obs.evidence[0].file_path if obs.evidence else ""
    return f"{obs.check_name}::{first_path}::{obs.event}"


def load_previous_snapshot(snapshot_path: Path) -> dict[str, dict]:
    if not snapshot_path.exists():
        return {}
    try:
        with open(snapshot_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_snapshot(snapshot_path: Path, observations: list[Observation]) -> None:
    data = {_observation_key(o): asdict(o) for o in observations}
    with open(snapshot_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def diff_against_previous(
    observations: list[Observation], previous: dict[str, dict]
) -> tuple[list[Observation], list[Observation], list[str]]:
    """Returns (new_observations, repeated_observations, resolved_event_keys)."""
    current_keys = {_observation_key(o) for o in observations}
    new_obs = [o for o in observations if _observation_key(o) not in previous]
    repeated_obs = [o for o in observations if _observation_key(o) in previous]
    resolved_keys = [k for k in previous if k not in current_keys]
    return new_obs, repeated_obs, resolved_keys


def _confidence_counts(observations: list[Observation]) -> dict[str, int]:
    counts = {Confidence.MATCH: 0, Confidence.MISMATCH: 0, Confidence.INSUFFICIENT_EVIDENCE: 0}
    for o in observations:
        counts[o.confidence] = counts.get(o.confidence, 0) + 1
    return counts


def render_report(
    observations: list[Observation],
    new_obs: list[Observation],
    repeated_obs: list[Observation],
    resolved_keys: list[str],
    scanned_repos: list[str],
    skipped_repos: list[str],
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = _confidence_counts(observations)
    lines: list[str] = []

    lines.append(f"# Observation Report — {now}")
    lines.append("")
    lines.append(
        "Generated by the Observation Agent implementation "
        "(`observation-agent/`), per "
        "`docs/proposals/AGENT-001-observation-agent/`. No file outside "
        "this report and its snapshot was written by this run."
    )
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"Scanned {len(scanned_repos)} repositories "
        f"({', '.join(scanned_repos) if scanned_repos else 'none'}); "
        f"{len(skipped_repos)} skipped "
        f"({', '.join(skipped_repos) if skipped_repos else 'none'}). "
        f"{len(observations)} total observations: {counts[Confidence.MISMATCH]} "
        f"MISMATCH, {counts[Confidence.INSUFFICIENT_EVIDENCE]} "
        f"INSUFFICIENT_EVIDENCE, {counts[Confidence.MATCH]} MATCH."
    )
    lines.append("")

    # New Observations
    lines.append("## New Observations")
    lines.append("")
    if new_obs:
        for o in new_obs:
            lines.extend(_render_observation(o))
    else:
        lines.append("None.")
    lines.append("")

    # Repeated Findings
    lines.append("## Repeated Findings")
    lines.append("")
    if repeated_obs:
        lines.append(
            "Present in the previous run and still present now — the "
            "underlying recommendation was not acted on, or has not yet "
            "been checked again."
        )
        lines.append("")
        for o in repeated_obs:
            lines.extend(_render_observation(o, short=True))
    else:
        lines.append("None.")
    lines.append("")

    # Resolved Findings
    lines.append("## Resolved Findings")
    lines.append("")
    if resolved_keys:
        for key in resolved_keys:
            lines.append(f"- `{key}` — present in the previous run, not found in this one.")
    else:
        lines.append("None.")
    lines.append("")

    # Risk Changes
    lines.append("## Risk Changes")
    lines.append("")
    lines.append(
        "Not computed by this MVP — requires tracking a severity value "
        "per finding across runs, which this implementation does not "
        "yet assign (see LIMITATIONS in README.md)."
    )
    lines.append("")

    # Confidence
    lines.append("## Confidence")
    lines.append("")
    lines.append(
        f"MATCH: {counts[Confidence.MATCH]} · "
        f"MISMATCH: {counts[Confidence.MISMATCH]} · "
        f"INSUFFICIENT_EVIDENCE: {counts[Confidence.INSUFFICIENT_EVIDENCE]}. "
        "No single aggregate score across repositories or findings — "
        "per PROP-0001's own explicit rule, inherited without exception."
    )
    lines.append("")

    # Evidence Links
    lines.append("## Evidence Links")
    lines.append("")
    if observations:
        for o in observations:
            for c in o.evidence_citations():
                lines.append(f"- {c}")
    else:
        lines.append("None.")
    lines.append("")

    # Recommended Actions
    lines.append("## Recommended Actions")
    lines.append("")
    actionable = [o for o in observations if o.recommended_action != "none — informational only"]
    if actionable:
        for o in actionable:
            lines.append(f"- **[{o.confidence}]** {o.recommended_action}")
    else:
        lines.append("None.")
    lines.append("")

    # Human Decisions Required
    lines.append("## Human Decisions Required")
    lines.append("")
    needing_human = [o for o in observations if o.human_needed]
    if needing_human:
        for o in needing_human:
            lines.append(f"- {o.event}")
    else:
        lines.append("None.")
    lines.append("")

    return "\n".join(lines)


def _render_observation(o: Observation, short: bool = False) -> list[str]:
    out = [f"### {o.event}", ""]
    out.append(f"- **Confidence**: {o.confidence}")
    if not short:
        out.append(f"- **Verification Method**: {o.verification_method}")
        out.append(f"- **Possible Interpretation**: {o.possible_interpretation}")
    out.append(f"- **Recommended Action**: {o.recommended_action}")
    out.append(f"- **Human Needed?**: {'YES' if o.human_needed else 'NO'}")
    if not short:
        for c in o.evidence_citations():
            out.append(f"  - Evidence: {c}")
    out.append("")
    return out
